services:
  api:
    build: .
    image: api-php-slim4:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
